---
- name: Creates directory
  file:
    path: ~/backend
    state: directory
    
- name: Copy dist
  copy:
    src: dist.zip
    dest: "~/backend/dist.zip"
  
- name: Unzip dists
  unarchive:
    src: ~/backend/dist.zip
    dest: ~/backend/
    remote_src: yes






     

    