---
- name: Creates directory
  file:
    path: ~/backend
    state: directory

- name: Zip dist
  archive:
    path: /root/project/backend/dist
    dest:  /root/project/.circleci/ansible/roles/deploy/files/dist.zip
    format: zip

- name: Copy dist
  become: true
  copy:
    src: "dist.zip"
    dest: "~/backend/dist.zip"
  
- name: Unzip dists
  unarchive:
    src: ~/backend/dist.zip
    dest: ~/backend/
    remote_src: yes






     

    