---
- name: Creates directory
  file:
    path: ~/backend
    state: directory

- name: Copy dist
  copy:
    src: dist.zip
    dest: "~/backend/dist.zip"
  
- name: "Unzip dist.zip"
  shell: |
    cd ~/backend
    unzip dist.zip

- name: "Unzip dist.zip"
  shell: |
      cd ~/backend
      ls 
  register: shell_result

- name: "Unzip dist.zip"
  debug:
    var: shell_result.stdout_lines

- name: "Install dependencies for project"
  shell: |
    cd ~/backend
    npm install

  
- name: "Executing node"
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
 
- name: "PM2 autostart"
  shell: |
    pm2 startup
    pm2 save




     

    