---
- name: Creates directory
  file:
    path: ~/backend
    state: directory

- name: Copy dist
  copy:
    src: dist.zip
    dest: "~/backend/dist.zip"
  
- name: "Unzip dist.zip"
  shell: |
    cd ~/backend
    unzip dist.zip
    rm -rf dist.zip
    ls

- name: "Executing node"
  shell: |
    cd ~/backend
    pm2 start main.js
 
- name: "PM2 autostart"
  shell: |
    pm2 startup
    pm2 save




     

    