---
- name: Creates directory
  file:
    path: ~/backend
    state: directory

- name: Copy dist
  become: true
  template:
    src:  project/.circleci/ansible/roles/deploy/files/dist/
    dest: ~/backend




     

    