---
- name: Creates directory
  file:
    path: ~/backend
    state: directory

- name: Zip dist
    archive:
      path:
        - /project/.circleci/ansible/roles/deploy/files/dist/
      dest:  /project/.circleci/ansible/roles/deploy/files/dist.zip
      format: zip

- name: Copy distss
  become: true
  copy:
    src:  /project/.circleci/ansible/roles/deploy/files/dist.zip
    dest: ~/backend/dist.zip
  
- name: Unzip distss
    unarchive:
      src: ~/backend/dist.zip
      dest: ~/backend
      remote_src: True






     

    