---
- name: Creates directory
  file:
    path: ~/backend
    state: directory

- name: Zip dist
  archive:
    path: /project/backend/dist
    dest:  /project/backend/dist.zip
    format: zip

- name: Copy distss
  become: true
  copy:
    src: "/project/backend/dist.zip"
    dest: "~/backend/dist.zip"
  
- name: Unzip distss
  unarchive:
    src: ~/backend/dist.zip
    dest: ~/backend
    remote_src: True






     

    