---
- name: Unarchive Backend
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/

- name: "List backend contents"
  shell: |
      ls 
  register: shell_result

- name: "installing dependencies"
  shell: |
      npm install
      npm build
  args:
    chdir: /home/ubuntu

- name: "Display as output"
  debug:
    var: shell_result.stdout_lines
    
- name: "Start Application"
  shell: |      
      pm2 start npm --name backend -- run start
  args:
    chdir: /home/ubuntu

- name: "List processes"
  shell: |      
      pm2 list
  register: pm2_result

- name: "Print in the debug console"
  debug:
    var: pm2_result.stdout_lines

  environment:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.js"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
 
 





     

    