---
- name: Creates directory
  file:
    path: ~/backend
    state: directory

- name: Copy dist
  copy:
    src: dist.tar.gz
    dest: "~/backend/dist.tar.gz"

- name: Copy dist
  unarchive:
    src: ~/backend/dist.tar.gz
    dest: ~/backend
    remote_src: True

- name: "List backend contents"
  shell: |
      cd ~/backend
      ls 
  register: shell_result

- name: "Display as output"
  debug:
    var: shell_result.stdout_lines
    
- name: stop backend service
  become: yes
  become_user: ubuntu
  changed_when: false
  ignore_errors: yes  
  command: pm2 stop all


- name: "Install dependencies for project"
  shell: |
    cd ~/backend
    npm install

- name: start backend service
  become: yes
  become_user: ubuntu
  changed_when: false
  command: pm2 start -f main.js
  args:
    chdir: ~/backend
  
- name: "List processes"
  shell: |      
      pm2 loyuiuyyu
  register: pm2_result

- name: "Print in the debug console"
  debug:
    var: pm2_result.stdout_lines

 
 





     

    