---
- name: Creates directory
  file:
    path: ~/backend
    state: directory

- name: Copy dist
  copy:
    src: dist.zip
    dest: "~/backend/dist.zip"
  
- name: "Unzip dist.zip"
  shell: |
    cd ~/backend
    unzip dist.zip
    rm -rf dist.zip

- name: "Unzip dist.zip"
  shell: |
    cd ~/backend/dist
    npm install
    npm run start
    npm run start:dev
    npm run webpack
    npm run start:hmr
    npm run start:prod






     

    